---
- name: Read time zone and if is not Moskow, change it.
  hosts: all
  gather_facts: false
  tasks:
  - name: get time zone
    shell: "timedatectl | grep \"Time zone\" | awk -F\": \" '{printf $2}' | sed 's/[[:blank:]]*$//'"
    register: timezone_stdout
  - name: show time zone
    debug: var=timezone_stdout.stdout
  - name: become a root and change time zone if not Moskow
    shell: "timedatectl set-timezone Europe/Moscow"
    become: yes
    when: timezone_stdout.stdout != "Europe/Moscow (MSK, +0300)"