---
- name:
  hosts: all
  become: true

  tasks:
    - name: Show npm version
      shell: "npm -v"

    - name: delete current folder
      shell: "rm -rf /home/zebra/radiochiptune"

    - name: Clone a repo 
      git:
        repo: https://github.com/zebra48r/radiochiptune.git
        dest: /home/zebra/radiochiptune
    
    - name: Update npm
      npm:
        path=/home/zebra/radiochiptune
    - name: npm install
      shell: "cd /home/zebra/radiochiptune && npm install"
      register: npm_install
    - debug: msg="{{ npm_install.stdout }}"

    - name: make build
      shell: "cd /home/zebra/radiochiptune && npm run-script build ."
      register: npm_build

    - debug: msg="{{ npm_build.stdout }}"

    - name: make build and run server 
      shell: "cd /home/zebra/radiochiptune && nohup serve -s build -l 4000 &"