---
- name:
  hosts: all
  become: true

  tasks:
    - name: Show npm version
      shell:
        cmd: npm -v
        args:
         executable: /bin/bash

    - name: delete current folder
      shell:
        cmd: rm -rf /home/zebra/radiochiptune
        args:
         executable: /bin/bash

    - name: Clone a repo 
      git:
        repo: https://github.com/zebra48r/radiochiptune.git
        dest: /home/zebra/radiochiptune
    
    - name: Update npm
      npm:
        path=/home/zebra/radiochiptune

    - name: make build and run server 
      shell:
        cmd: cd /home/zebra/radiochiptune && npm build && nohup serve -s build -l 4000 &
        args:
         executable: /bin/bash